FROM node:20-alpine

LABEL org.opencontainers.image.source=https://github.com/qa-tech-training/qadevoprac3-capstone-lab-starter

USER 1000

WORKDIR app

COPY package.json .
RUN npm install
COPY . .



# TODO: add the instructions needed to copy the package.json, install dependencies, and copy the server.js file

CMD ["node", "server.js"]
