name: Validate Helm Chart

on:
  push:
    branches:
    - main

jobs:
  validate-chart:
    runs-on: ubuntu-latest

    steps:
    - name: Install Terrascan
        run: |
          curl -L https://github.com/tenable/terrascan/releases/latest/download/terrascan_Linux_x86_64.tar.gz -o terrascan.tar.gz
          tar -xzf terrascan.tar.gz
          sudo install terrascan /usr/local/bin/terrascan
          terrascan version
          
    - name: validate
      run: |
        # TODO: add the necessary commands here to install terrascan
        cd terraform/
        terrascan scan -i helm
